logging:
  level:
    org:
      springframework:
        jdbc:
          core: info

spring:
  profiles:
    include: oauth
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_practice?serverTimezone=UTC&useSSL=false&characterEncoding=utf8&characterSetResults=utf8&rewriteBatchedStatements=true
    username: root
    password: orcl
  session:
    store-type: jdbc

#spring:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL