logging:
  level:
    org:
      springframework:
        jdbc:
          core: info

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL

#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        ddl-auto: create
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring_boot_practice?serverTimezone=UTC&useSSL=false&characterEncoding=utf8&characterSetResults=utf8&rewriteBatchedStatements=true
#    username: root
#    password: orcl
#  devtools:
#    livereload:
#      enabled: true