name: Java CI with Gradle

# Workflow가 실행되는 event 목록: master 브랜치에 push or PR
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  S3_BUCKET_NAME: spring-boot-practice-build

jobs:
  build:
    # Runner 실행 환경: 우분투
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Make Dir
        run: mkdir -p deploy

      - name: Move Jar File
        run: mv spring-boot-practice.zip deploy/spring-boot-practice.zip

      - name: Copy appspec.yml
        run: cp ../../appspec.yml ./deploy

      - name: Make zip file
        run: zip -r ./spring-boot-practice.zip .
        shell: bash

      - name: AWS Setting
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./spring-boot-practice.zip s3://$S3_BUCKET_NAME/spring-boot-practice.zip

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws deploy create-deployment --application-name spring-boot-practice --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name dev --s3-location bucket=spring-boot-practice-build,key=smart-mirror/spring-boot-practice.zip,bundleType=zip